/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lib;

public class Teste {

    public static void very(boolean expressao, boolean experado){
        try{
            if(expressao != experado){
                throw new Exception("Erro: valor não retornado o experado;");
            }
        }catch(Exception e){
			e.printStackTrace();
		}
    }

    public static void testeAll(){
        // SkipList.teste();
        // SkipList2.teste();
        // LossyCounting.teste();
        // TDigest.teste();
        // QuotientFilter.teste();
        // CuckooFilter.teste();
        HyperLogLog.teste();
        // CountMinSketch.teste();
        // BloomFilter.teste();
    }

}