/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // SkipList.teste();
        // SkipList2.teste();
        // LossyCounting.teste();
        // TDigest.teste();
        // QuotientFilter.teste();
        // CuckooFilter.teste();
        // HyperLogLog.teste();
        CountMinSketch.teste();
    }
}
