/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Objects;

/**
 * wrapper para criar hash para objetos;
 */
class ObjToHash {

    public static int hash(Object object) {
        return Objects.hash(object);
    }
}