/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Teste {

    public static void very(boolean expressao, boolean experado){
        try{
            if(expressao != experado){
                throw new Exception("Erro: valor não retornado o experado;");
            }
        }catch(Exception e){
			e.printStackTrace();
		}
    }

}